/**
 * Built-in document presets in the new `DocumentPreset` format.
 *
 * Each preset is a complete style definition. Built-in presets are
 * immutable — user customizations are stored as separate `customPresets`
 * entries in localStorage.
 */

import type { DocumentPreset } from './documentPreset';

/** Common defaults shared by all presets, overridden where appropriate. */
const COMMON_COLORS = {
  background: '#ffffff',
  surface: '#f6f8fa',
  primaryText: '#1f2328',
  secondaryText: '#59636e',
  mutedText: '#818b98',
  accent: '#0969da',
  headings: '#0f172a',
  borders: '#d0d7de',
  codeBackground: '#f6f8fa',
  codeText: '#24292e',
  codeHeader: '#586069',
  codeBorder: '#d0d7de',
  lineNumbers: '#9198a1',
  links: '#0969da',
  success: '#1a7f37',
  warning: '#9a6700',
  error: '#cf222e',
};

export const BUILT_IN_DOCUMENT_PRESETS: DocumentPreset[] = [
  {
    id: 'university',
    name: 'University',
    description:
      'Professional serif typography with readable code blocks, line numbers, table of contents, and page breaks between files. Ideal for academic submissions.',
    builtIn: true,
    syntaxTheme: 'github-light',
    page: {
      size: 'A4',
      landscape: false,
      marginTopMm: 25,
      marginRightMm: 20,
      marginBottomMm: 25,
      marginLeftMm: 25,
      headerSpacingMm: 10,
      footerSpacingMm: 10,
      pageHeader: null,
      pageFooter: 'Page {page} of {pages}',
    },
    typography: {
      bodyFont: 'Times New Roman',
      bodyFontSizePt: 12,
      bodyColor: '#1f2328',
      paragraphSpacingPt: 6,
      lineSpacing: 1.4,
    },
    headings: {
      title: { font: 'Times New Roman', sizePt: 28, weight: 'bold', italic: false, color: '#0f172a', alignment: 'center', spaceBeforePt: 0, spaceAfterPt: 12, numbered: false },
      h1: { font: 'Times New Roman', sizePt: 20, weight: 'bold', italic: false, color: '#0f172a', alignment: 'left', spaceBeforePt: 12, spaceAfterPt: 6, numbered: true },
      h2: { font: 'Times New Roman', sizePt: 15, weight: 'bold', italic: false, color: '#0f172a', alignment: 'left', spaceBeforePt: 10, spaceAfterPt: 5, numbered: true },
      h3: { font: 'Times New Roman', sizePt: 12, weight: 'bold', italic: false, color: '#1e293b', alignment: 'left', spaceBeforePt: 8, spaceAfterPt: 4, numbered: true },
      h4: { font: 'Times New Roman', sizePt: 11, weight: 'semibold', italic: false, color: '#1e293b', alignment: 'left', spaceBeforePt: 6, spaceAfterPt: 3, numbered: true },
    },
    code: {
      font: 'Courier New',
      fontSizePt: 9,
      lineHeight: 1.25,
      textColor: '#24292e',
      backgroundColor: '#f6f8fa',
      borderColor: '#d0d7de',
      borderWidthPt: 0.5,
      borderRadiusPt: 0,
      paddingPt: 8,
      showLineNumbers: true,
      lineNumberColor: '#9198a1',
      lineNumberBackground: null,
      wrapLongLines: true,
      blockSpacingBeforePt: 4,
      blockSpacingAfterPt: 8,
    },
    fileHeaders: {
      show: true,
      showFileName: true,
      showRelativePath: true,
      showLanguageLabel: true,
      showFileSize: true,
      showLineCount: false,
      background: 'transparent',
      textColor: '#586069',
      borderBottom: true,
      borderColor: '#d0d7de',
      font: 'Courier New',
      fontSizePt: 8,
      bold: true,
    },
    projectHeaders: {
      showTitle: true,
      showPath: false,
      showMetadata: true,
      font: 'Times New Roman',
      sizePt: 20,
      weight: 'bold',
      color: '#0f172a',
      spaceBeforePt: 12,
      spaceAfterPt: 6,
      uppercase: false,
    },
    titlePage: {
      enabled: true,
      showTitle: true,
      showSubtitle: false,
      showAuthor: true,
      showCourse: true,
      showUniversity: true,
      showDate: true,
      showVersion: true,
      showDescription: true,
    },
    colors: { ...COMMON_COLORS },
    includeToc: true,
    includeProjectStructure: true,
    pageBreakBetweenFiles: true,
    metadata: {
      title: 'Project Report',
      author: 'Student Name',
    },
  },

  {
    id: 'developer',
    name: 'Developer',
    description:
      'Modern sans-serif typography with compact code blocks. Code-focused, no TOC, no title page. Good for technical documentation and internal reports.',
    builtIn: true,
    syntaxTheme: 'github-dark',
    page: {
      size: 'A4',
      landscape: false,
      marginTopMm: 18,
      marginRightMm: 18,
      marginBottomMm: 18,
      marginLeftMm: 18,
      headerSpacingMm: 8,
      footerSpacingMm: 8,
      pageHeader: null,
      pageFooter: '{page}',
    },
    typography: {
      bodyFont: 'Inter',
      bodyFontSizePt: 11,
      bodyColor: '#1f2328',
      paragraphSpacingPt: 4,
      lineSpacing: 1.35,
    },
    headings: {
      title: { font: 'Inter', sizePt: 24, weight: 'bold', italic: false, color: '#0f172a', alignment: 'left', spaceBeforePt: 0, spaceAfterPt: 10, numbered: false },
      h1: { font: 'Inter', sizePt: 18, weight: 'bold', italic: false, color: '#0f172a', alignment: 'left', spaceBeforePt: 10, spaceAfterPt: 5, numbered: true },
      h2: { font: 'Inter', sizePt: 14, weight: 'semibold', italic: false, color: '#0f172a', alignment: 'left', spaceBeforePt: 8, spaceAfterPt: 4, numbered: true },
      h3: { font: 'Inter', sizePt: 12, weight: 'semibold', italic: false, color: '#1e293b', alignment: 'left', spaceBeforePt: 6, spaceAfterPt: 3, numbered: false },
      h4: { font: 'Inter', sizePt: 11, weight: 'medium', italic: false, color: '#1e293b', alignment: 'left', spaceBeforePt: 4, spaceAfterPt: 2, numbered: false },
    },
    code: {
      font: 'JetBrains Mono',
      fontSizePt: 8.5,
      lineHeight: 1.2,
      textColor: '#e6edf3',
      backgroundColor: '#24292e',
      borderColor: null,
      borderWidthPt: 0,
      borderRadiusPt: 3,
      paddingPt: 8,
      showLineNumbers: true,
      lineNumberColor: '#7d8590',
      lineNumberBackground: null,
      wrapLongLines: false,
      blockSpacingBeforePt: 3,
      blockSpacingAfterPt: 6,
    },
    fileHeaders: {
      show: true,
      showFileName: true,
      showRelativePath: true,
      showLanguageLabel: true,
      showFileSize: false,
      showLineCount: false,
      background: 'transparent',
      textColor: '#7d8590',
      borderBottom: true,
      borderColor: '#30363d',
      font: 'JetBrains Mono',
      fontSizePt: 8,
      bold: true,
    },
    projectHeaders: {
      showTitle: true,
      showPath: true,
      showMetadata: false,
      font: 'Inter',
      sizePt: 18,
      weight: 'bold',
      color: '#0f172a',
      spaceBeforePt: 10,
      spaceAfterPt: 5,
      uppercase: false,
    },
    titlePage: {
      enabled: false,
      showTitle: true,
      showSubtitle: false,
      showAuthor: true,
      showCourse: false,
      showUniversity: false,
      showDate: true,
      showVersion: true,
      showDescription: false,
    },
    colors: { ...COMMON_COLORS, codeBackground: '#24292e', codeText: '#e6edf3', codeHeader: '#7d8590', codeBorder: '#30363d', lineNumbers: '#7d8590' },
    includeToc: false,
    includeProjectStructure: true,
    pageBreakBetweenFiles: false,
  },

  {
    id: 'minimal',
    name: 'Minimal',
    description:
      'Simple typography, minimal decoration, maximum code density. Good for archiving a small project as a single document.',
    builtIn: true,
    syntaxTheme: 'github-light',
    page: {
      size: 'A4',
      landscape: false,
      marginTopMm: 15,
      marginRightMm: 15,
      marginBottomMm: 15,
      marginLeftMm: 15,
      headerSpacingMm: 6,
      footerSpacingMm: 6,
      pageHeader: null,
      pageFooter: null,
    },
    typography: {
      bodyFont: 'Helvetica',
      bodyFontSizePt: 10,
      bodyColor: '#1f2328',
      paragraphSpacingPt: 3,
      lineSpacing: 1.3,
    },
    headings: {
      title: { font: 'Helvetica', sizePt: 18, weight: 'bold', italic: false, color: '#0f172a', alignment: 'left', spaceBeforePt: 0, spaceAfterPt: 6, numbered: false },
      h1: { font: 'Helvetica', sizePt: 14, weight: 'bold', italic: false, color: '#0f172a', alignment: 'left', spaceBeforePt: 8, spaceAfterPt: 4, numbered: false },
      h2: { font: 'Helvetica', sizePt: 12, weight: 'bold', italic: false, color: '#1e293b', alignment: 'left', spaceBeforePt: 6, spaceAfterPt: 3, numbered: false },
      h3: { font: 'Helvetica', sizePt: 11, weight: 'semibold', italic: false, color: '#1e293b', alignment: 'left', spaceBeforePt: 4, spaceAfterPt: 2, numbered: false },
      h4: { font: 'Helvetica', sizePt: 10, weight: 'medium', italic: false, color: '#1e293b', alignment: 'left', spaceBeforePt: 3, spaceAfterPt: 1, numbered: false },
    },
    code: {
      font: 'Courier New',
      fontSizePt: 8,
      lineHeight: 1.15,
      textColor: '#24292e',
      backgroundColor: '#ffffff',
      borderColor: '#e5e7eb',
      borderWidthPt: 0.5,
      borderRadiusPt: 0,
      paddingPt: 4,
      showLineNumbers: false,
      lineNumberColor: '#9198a1',
      lineNumberBackground: null,
      wrapLongLines: false,
      blockSpacingBeforePt: 2,
      blockSpacingAfterPt: 4,
    },
    fileHeaders: {
      show: true,
      showFileName: true,
      showRelativePath: true,
      showLanguageLabel: false,
      showFileSize: false,
      showLineCount: false,
      background: 'transparent',
      textColor: '#586069',
      borderBottom: false,
      borderColor: '#e5e7eb',
      font: 'Courier New',
      fontSizePt: 7,
      bold: true,
    },
    projectHeaders: {
      showTitle: true,
      showPath: false,
      showMetadata: false,
      font: 'Helvetica',
      sizePt: 14,
      weight: 'bold',
      color: '#0f172a',
      spaceBeforePt: 8,
      spaceAfterPt: 4,
      uppercase: false,
    },
    titlePage: {
      enabled: false,
      showTitle: true,
      showSubtitle: false,
      showAuthor: false,
      showCourse: false,
      showUniversity: false,
      showDate: false,
      showVersion: false,
      showDescription: false,
    },
    colors: { ...COMMON_COLORS, codeBackground: '#ffffff' },
    includeToc: false,
    includeProjectStructure: false,
    pageBreakBetweenFiles: false,
  },

  {
    id: 'dark-code',
    name: 'Dark Code',
    description:
      'Readable document with darker code blocks. Body text stays light for print friendliness, but code uses a dark theme for screen viewing.',
    builtIn: true,
    syntaxTheme: 'one-dark-pro',
    page: {
      size: 'A4',
      landscape: false,
      marginTopMm: 20,
      marginRightMm: 20,
      marginBottomMm: 20,
      marginLeftMm: 20,
      headerSpacingMm: 8,
      footerSpacingMm: 8,
      pageHeader: null,
      pageFooter: 'Page {page}',
    },
    typography: {
      bodyFont: 'Inter',
      bodyFontSizePt: 11,
      bodyColor: '#1f2328',
      paragraphSpacingPt: 4,
      lineSpacing: 1.35,
    },
    headings: {
      title: { font: 'Inter', sizePt: 26, weight: 'bold', italic: false, color: '#0f172a', alignment: 'center', spaceBeforePt: 0, spaceAfterPt: 12, numbered: false },
      h1: { font: 'Inter', sizePt: 18, weight: 'bold', italic: false, color: '#0f172a', alignment: 'left', spaceBeforePt: 12, spaceAfterPt: 6, numbered: true },
      h2: { font: 'Inter', sizePt: 14, weight: 'bold', italic: false, color: '#1e293b', alignment: 'left', spaceBeforePt: 10, spaceAfterPt: 5, numbered: true },
      h3: { font: 'Inter', sizePt: 12, weight: 'semibold', italic: false, color: '#1e293b', alignment: 'left', spaceBeforePt: 8, spaceAfterPt: 4, numbered: true },
      h4: { font: 'Inter', sizePt: 11, weight: 'medium', italic: false, color: '#1e293b', alignment: 'left', spaceBeforePt: 6, spaceAfterPt: 3, numbered: false },
    },
    code: {
      font: 'JetBrains Mono',
      fontSizePt: 9,
      lineHeight: 1.3,
      textColor: '#abb2bf',
      backgroundColor: '#282c34',
      borderColor: '#3e4451',
      borderWidthPt: 0.5,
      borderRadiusPt: 4,
      paddingPt: 10,
      showLineNumbers: true,
      lineNumberColor: '#5c6370',
      lineNumberBackground: '#21252b',
      wrapLongLines: false,
      blockSpacingBeforePt: 4,
      blockSpacingAfterPt: 8,
    },
    fileHeaders: {
      show: true,
      showFileName: true,
      showRelativePath: true,
      showLanguageLabel: true,
      showFileSize: true,
      showLineCount: false,
      background: '#21252b',
      textColor: '#abb2bf',
      borderBottom: true,
      borderColor: '#3e4451',
      font: 'JetBrains Mono',
      fontSizePt: 8,
      bold: true,
    },
    projectHeaders: {
      showTitle: true,
      showPath: true,
      showMetadata: false,
      font: 'Inter',
      sizePt: 18,
      weight: 'bold',
      color: '#0f172a',
      spaceBeforePt: 12,
      spaceAfterPt: 6,
      uppercase: false,
    },
    titlePage: {
      enabled: true,
      showTitle: true,
      showSubtitle: false,
      showAuthor: true,
      showCourse: false,
      showUniversity: false,
      showDate: true,
      showVersion: true,
      showDescription: true,
    },
    colors: { ...COMMON_COLORS, codeBackground: '#282c34', codeText: '#abb2bf', codeHeader: '#abb2bf', codeBorder: '#3e4451', lineNumbers: '#5c6370' },
    includeToc: true,
    includeProjectStructure: true,
    pageBreakBetweenFiles: true,
  },
];

export const DEFAULT_DOCUMENT_PRESET_ID = 'university';

export function getBuiltInPreset(id: string): DocumentPreset | undefined {
  return BUILT_IN_DOCUMENT_PRESETS.find((p) => p.id === id);
}

export function getDefaultDocumentPreset(): DocumentPreset {
  return BUILT_IN_DOCUMENT_PRESETS[0];
}
